language: node_js
node_js: "stable"
sudo: false
install:
 - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
 - dnvm upgrade -r coreclr
script:
 - dnu restore
 - dnx -p UnitTests/project.json test
 - dnx -p IntranetGJAK/project.json web
