sudo: false
services:
 - docker
script:
 - docker build -t intranetgjak .
 - docker run -t -d -p 8080:5000 intranetgjak
env:
 matrix:
  - ASPNET_VERSION=latest
  - ASPNET_VERSION=1.0.0-beta8-coreclr
  - ASPNET_VERSION=1.0.0-beta8
