language: csharp
#sudo: false
services:
 - docker
install:
 - sed -i 's/microsoft\/aspnet\:latest/${ASPNET_VERSION}/g' Dockerfile
 - docker build -t intranetgjak .
script:
 - docker run -t -d -p 8080:5000 intranetgjak
env:
 matrix:
  - ASPNET_VERSION="microsoft/aspnet:latest"
  - ASPNET_VERSION="microsoft/aspnet:1.0.0-beta8-coreclr"
  - ASPNET_VERSION="microsoft/aspnet:1.0.0-beta8"
