language: node_js
sudo: true
env:
  - R=coreclr
  - R=mono
install:
  - projectdir="$PWD"
  - sudo apt-get update -qq
  - sudo apt-get install -qq unzip curl
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh
  - source ~/.dnx/dnvm/dnvm.sh
  - sudo apt-get install -qq libunwind8 gettext libssl-dev libcurl3-dev zlib1g libicu-dev
  - dnvm upgrade -r $R
  - cd "$projectdir"
script:
  - dnu restore
  - dnu -p IntranetGJAK/project.json publish
  - dnx -p UnitTests/project.json test
