version: 0.1.{build}
branches:
  except:
  - gh-pages
os: Visual Studio 2015
configuration:
- Debug
- Release
platform: Any CPU
shallow_clone: true
environment:
  DNX_FEED: https://www.nuget.org/api/v2
init:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- cmd: dnvm upgrade
- cmd: SET
install:
- cmd: dnu restore
- cmd: cd IntranetGJAK
- cmd: npm install
build_script:
- cmd: cd IntranetGJAK
- cmd: dnu publish
after_build:
- cmd: 7z a IntranetGJAK.zip %APPVEYOR_BUILD_FOLDER%\artifacts
test_script:
- cmd: dnx -p UnitTests\ test
artifacts:
- path: IntranetGJAK.zip
  name: IntranetGJAK
cache:
 - IntranetGJAK\wwwroot\lib
 - IntranetGJAK\node_modules
 - %APPDATA%\npm-cache