version: 0.1.{build}
branches:
  except:
  - gh-pages
os: Visual Studio 2015
configuration:
- Debug
- Release
platform: Any CPU
shallow_clone: true
before_build:
- cmd: dnvm upgrade
build:
  project: IntranetGJAK.sln
  publish_wap: true
  parallel: true
  verbosity: minimal
artifacts:
- path: '*'
deploy:
- provider: Environment
  name: VOSTRO470
  on:
    branch: master
