version: 0.1.{build}
branches:
  except:
  - gh-pages
os: Visual Studio 2015
configuration:
- Debug
- Release
platform: Any CPU
shallow_clone: true
environment:
  DNX_FEED: https://www.nuget.org/api/v2
before_build:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- cmd: dnvm upgrade
- cmd: dnu restore
build:
  project: IntranetGJAK.sln
  publish_wap: true
  parallel: true
  verbosity: minimal
test_script:
- cmd: dnx -p UnitTests/ test
artifacts:
- path: artifacts/**/*
deploy:
- provider: Environment
  name: VOSTRO470
  on:
    branch: master
