version: 1.0.{build}
branches:
  except:
  - gh-pages
os: Visual Studio 2015
configuration:
- Debug
- Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- cmd: nuget restore
build:
  project: Backload.Demo.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: Backload.Demo\bin
deploy: off